### PR TITLE
Fix creation of spectral function space from TransLocal (fixes #249)

### LINKED ISSUE #249: Failure in atlas_fctest_trans_unstructured
### What happened?

Running atlas_fctest_trans_unstructured with certain configs gives this failure:

183/216 Test #183: atlas_fctest_trans_unstructured ...........................Subprocess aborted***Exception:   0.23 sec
Runtime Error: *** Arithmetic exception: Floating overflow - aborting
/home/users/david.davies/cylc-run/mi-bg671/work/1/get_source_atlas/atlas/src/atlas_f/trans/atlas_Trans_module.F90, line 352: Error occurred in ATLAS_TRANS_MODULE:INVTRANS_VORDIV2WIND_FIELD
/data/users/david.davies/cylc-run/mi-bg671/work/1/get_source_atlas/atlas/src/tests/trans/fctest_trans_unstructured.F90, line 84: Called by FCTEST_ATLAS_TRANS_UNSTR:TEST_TRANS
/home/users/david.davies/cylc-run/mi-bg671/work/1/build_atlas_nag/build/src/tests/trans/fctest_trans_unstructured_main.F90, line 21: Called by RUN_FCTEST_ATLAS_TRANS_UNSTR

### What are the steps to reproduce the bug?

Building and runinng with NAG/GCC, building with ectrans support.  However this failure only occurs with some configs.  I don't think the NAG is particularly relevant here (see below)(

### Version

Head

### Platform (OS and architecture)

Linus

### Relevant log output

_No response_

### Accompanying data

_No response_

### Organisation

Met Office

### PR DESCRIPTION
**Pull request by wdeconinck**
This fixes #249 .
The problem was that the functionspace::Spectral created via the TransLocal api was creating a new functionspace with truncation == 1. 
This was due to an older removed API that could create the Spectral functionspace using a Trans object. An implicit conversion to 1 of this object resulted in truncation == 1.

### CODE REVIEW

File: src/atlas/trans/local/TransLocal.cc [hunk 1]
```diff
@@ -800,7 +800,7 @@ TransLocal::~TransLocal() {
 
 const functionspace::Spectral& TransLocal::spectral() const {
     if (not spectral_) {
-        spectral_ = functionspace::Spectral(Trans(this));
+        spectral_ = functionspace::Spectral( truncation() );
```
Comment (wdeconinck) [inline src/atlas/trans/local/TransLocal.cc:803]: This is the bug.
